//
//  SDZStockQuoteExample.h
//
//  Provides example and test runs the service's proxy methods.
//  Generated by Sudz-C (https://github.com/jkichline/sudzc)
//

@interface SDZStockQuoteExample : NSObject

- (void)run;

@end
