//
//  SDZStockQuoteExample.m
//
//  Provides example and test runs the service's proxy methods.
//  Generated by Sudz-C (https://github.com/jkichline/sudzc)
//

#import "SDZStockQuoteExample.h"
#import "SDZStockQuote.h"

@implementation SDZStockQuoteExample

- (void)run
{
  // Create the service
  SDZStockQuote *service = [SDZStockQuote service];
  service.logging = YES;
  // service.username = @"username";
  // service.password = @"password";

  // Returns NSString *Get Stock quote for a company Symbol
  [service GetQuote:self action:@selector(GetQuoteHandler:) symbol:@""];
  
}

// Handle the response from GetQuote
- (void)GetQuoteHandler:(id)value
{
    // Handle errors
    if ([value isKindOfClass:[NSError class]]) {
        NSLog(@"%@", value);
        return;
    }

    // Handle faults
    if ([value isKindOfClass:[SoapFault class]]) {
        NSLog(@"%@", value);
        return;
    }
      
    // Do something with the NSString * result
    NSString * result = (NSString *)value;
    NSLog(@"GetQuote returned the value: %@", result);
}
  
@end
