//
//  SudzCExamplesAppDelegate.m
//
//  An example application for the generated data
//  Generated by Sudz-C (https://github.com/jkichline/sudzc)
//

#import "SudzCExamplesAppDelegate.h"
#import "SDZStockQuoteExample.h"

@implementation SudzCExamplesAppDelegate

- (void)applicationDidFinishLaunching:(UIApplication *)application
{
    SDZStockQuoteExample *example1 = [[SDZStockQuoteExample alloc] init];
    [example1 run];
}

@end
