//
//  SudzCExamplesAppDelegate.h
//
//  An example application for the generated data
//  Generated by Sudz-C (https://github.com/jkichline/sudzc)
//

#import <UIKit/UIKit.h>

@interface SudzCExamplesAppDelegate : UIResponder <UIApplicationDelegate>

@property (nonatomic, strong) IBOutlet UIWindow *window;

@end
